//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VXInstaller.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VXInstaller.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The install directory for the plugins could not be determined. Please select it manually..
        /// </summary>
        internal static string InstallDirTextError {
            get {
                return ResourceManager.GetString("InstallDirTextError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the install directory for the plugins. If this is not correct, please select the correct directory..
        /// </summary>
        internal static string InstallDirTextFound {
            get {
                return ResourceManager.GetString("InstallDirTextFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin(s) could not be installed..
        /// </summary>
        internal static string InstallNone {
            get {
                return ResourceManager.GetString("InstallNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all plugins could be installed. The following plugins have been installed: {0}.
        /// </summary>
        internal static string InstallPartial {
            get {
                return ResourceManager.GetString("InstallPartial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All plugins have been installed..
        /// </summary>
        internal static string InstallSuccess {
            get {
                return ResourceManager.GetString("InstallSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No plugins could be found. Please make sure the plugin directory is provided with this installer..
        /// </summary>
        internal static string PluginsError {
            get {
                return ResourceManager.GetString("PluginsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the plugins to be installed:.
        /// </summary>
        internal static string PluginsFound {
            get {
                return ResourceManager.GetString("PluginsFound", resourceCulture);
            }
        }
    }
}
